name: macOS
on: push

jobs:
    build:
        runs-on: macOS-latest
        steps:
        - uses: actions/checkout@v1
        - name: Install build deps
          run: brew install automake
        - name: Build
          run: |
              ./configure
              make
